name: CDK Pipeline

on:
  push:
    branches:
      - master
      - dinesh
  pull_request:
    branches:
      - master
      - dinesh

jobs:
  cdk-diff-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Bootstrap AWS environment
        run: cdk bootstrap

      - name: Install CDK dependencies
        run: npm install

      - name: Deploy CDK stack
        run: cdk deploy --require-approval never
